name: amazon-fine-food-reviews
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - spacy
  - jupyter
  - wordcloud
  - beautifulsoup4
  - pip
  - pip:
      - textblob
      - tqdm
      - xgboost
      - lightgbm
